-- Tarakeswar Fresh Fish FINAL PRODUCTION additions
-- Run this ONCE in Supabase SQL Editor after the existing MASTER_FINAL_SETUP.sql.

alter table public.orders add column if not exists delivery_partner_id uuid;
create index if not exists idx_orders_delivery_partner_status on public.orders(delivery_partner_id,status,delivery_date);

-- Delivery partner profile security
alter table public.delivery_partner_profiles enable row level security;
drop policy if exists "delivery partner own profile" on public.delivery_partner_profiles;
create policy "delivery partner own profile" on public.delivery_partner_profiles
for select to authenticated using(user_id = auth.uid());

-- Push subscription storage
create table if not exists public.push_subscriptions(
 id bigint generated by default as identity primary key,
 customer_id uuid null,
 guest_id text null,
 endpoint text not null unique,
 p256dh text not null,
 auth text not null,
 user_agent text,
 enabled boolean not null default true,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);
alter table public.push_subscriptions enable row level security;
drop policy if exists "push own insert" on public.push_subscriptions;
create policy "push own insert" on public.push_subscriptions for insert to anon,authenticated with check(true);
drop policy if exists "push public update" on public.push_subscriptions;
create policy "push public update" on public.push_subscriptions for update to anon,authenticated using(true) with check(true);

-- Customer notification preferences
create table if not exists public.notification_preferences(
 id bigint generated by default as identity primary key,
 guest_id text unique,
 customer_id uuid null,
 enabled boolean not null default true,
 offers boolean not null default true,
 orders boolean not null default true,
 stock boolean not null default true,
 festivals boolean not null default true,
 updated_at timestamptz not null default now()
);
alter table public.notification_preferences enable row level security;
drop policy if exists "public notification preferences" on public.notification_preferences;
create policy "public notification preferences" on public.notification_preferences for all to anon,authenticated using(true) with check(true);

-- Fast lookup indexes
create index if not exists idx_push_subscriptions_enabled on public.push_subscriptions(enabled);
create index if not exists idx_push_subscriptions_guest on public.push_subscriptions(guest_id);
create index if not exists idx_notification_preferences_guest on public.notification_preferences(guest_id);

-- Realtime for fast live dashboards (safe to re-run)
do $$ begin
  begin alter publication supabase_realtime add table public.orders; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.offers; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.fish; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.delivery_locations; exception when duplicate_object then null; end;
end $$;
