-- TARAKESWAR FRESH FISH - MASTER FINAL SETUP
-- Run ONCE in Supabase SQL Editor.
-- This is additive and uses IF NOT EXISTS where possible.

-- Customer profile fields
alter table if exists public.customers add column if not exists date_of_birth date;
alter table if exists public.customers add column if not exists gender text;
alter table if exists public.customers add column if not exists profile_photo_url text;
alter table if exists public.customers add column if not exists anniversary_date date;
alter table if exists public.customers add column if not exists landmark text;
alter table if exists public.customers add column if not exists email text;

-- Banner automation
create table if not exists public.banner_assets(
 id uuid primary key default gen_random_uuid(), title text not null,
 description text, price numeric(12,2), image_url text not null,
 share_text text, is_active boolean not null default true,
 created_at timestamptz not null default now()
);
alter table public.banner_assets enable row level security;
drop policy if exists "public read active banners" on public.banner_assets;
create policy "public read active banners" on public.banner_assets for select to anon,authenticated using (is_active=true);
drop policy if exists "admin manage banners" on public.banner_assets;
create policy "admin manage banners" on public.banner_assets for all to authenticated using (true) with check (true);
create index if not exists idx_banner_assets_created on public.banner_assets(created_at desc);

insert into storage.buckets(id,name,public) values('banners','banners',true) on conflict(id) do update set public=true;
drop policy if exists "public read banners" on storage.objects;
create policy "public read banners" on storage.objects for select to anon,authenticated using(bucket_id='banners');

-- Saved carts
create table if not exists public.cart_drafts(
 id uuid primary key default gen_random_uuid(), guest_id text not null unique,
 customer_id uuid null, customer_name text, mobile text, area text,
 items jsonb not null default '[]'::jsonb, total numeric(12,2) not null default 0,
 updated_at timestamptz not null default now()
);
alter table public.cart_drafts enable row level security;
drop policy if exists "public upsert cart drafts" on public.cart_drafts;
create policy "public upsert cart drafts" on public.cart_drafts for all to anon,authenticated using(true) with check(true);

-- Wishlist sync
create table if not exists public.wishlist_items(
 id uuid primary key default gen_random_uuid(), guest_id text not null,
 customer_id uuid null, product_id bigint not null, created_at timestamptz not null default now(),
 unique(guest_id,product_id)
);
alter table public.wishlist_items enable row level security;
drop policy if exists "public wishlist access" on public.wishlist_items;
create policy "public wishlist access" on public.wishlist_items for all to anon,authenticated using(true) with check(true);

-- Delivery partner profile / earnings / surge controls
create table if not exists public.delivery_partner_profiles(
 id uuid primary key default gen_random_uuid(), user_id uuid unique,
 name text not null, mobile text, photo_url text, vehicle text, active boolean not null default true,
 login_at timestamptz, logout_at timestamptz, base_pay numeric(12,2) not null default 30,
 surge_multiplier numeric(6,2) not null default 1, rain_surge numeric(12,2) not null default 0,
 total_earnings numeric(12,2) not null default 0, settings jsonb not null default '{}'::jsonb
);
alter table public.delivery_partner_profiles enable row level security;

-- Live delivery locations
create table if not exists public.delivery_locations(
 id bigint generated by default as identity primary key, order_id uuid not null,
 rider_id uuid, lat double precision not null, lng double precision not null,
 accuracy double precision, heading double precision, speed double precision,
 created_at timestamptz not null default now()
);
create index if not exists idx_delivery_locations_order_time on public.delivery_locations(order_id,created_at desc);
alter table public.delivery_locations enable row level security;
drop policy if exists "public read delivery locations" on public.delivery_locations;
create policy "public read delivery locations" on public.delivery_locations for select to anon,authenticated using(true);
drop policy if exists "auth write delivery locations" on public.delivery_locations;
create policy "auth write delivery locations" on public.delivery_locations for insert to authenticated with check(true);

-- Automation settings, manually customizable from Admin later
create table if not exists public.automation_settings(
 id integer primary key default 1,
 banner_enabled boolean not null default true,
 banner_interval_minutes integer not null default 1440,
 feedback_enabled boolean not null default true,
 delivery_whatsapp_enabled boolean not null default true,
 rain_surge_enabled boolean not null default true,
 rain_surge_amount numeric(12,2) not null default 20,
 gps_interval_seconds integer not null default 10,
 updated_at timestamptz not null default now()
);
insert into public.automation_settings(id) values(1) on conflict(id) do nothing;

-- Performance indexes
create index if not exists idx_fish_available on public.fish(available);
create index if not exists idx_fish_category on public.fish(category);
create index if not exists idx_offers_enabled_dates on public.offers(enabled,start_at,end_at);

-- Product read permission
alter table if exists public.fish enable row level security;
drop policy if exists "public can read available fish" on public.fish;
create policy "public can read available fish" on public.fish for select to anon,authenticated using(available=true or available is null);
grant select on table public.fish to anon,authenticated;

-- Cart RPC fallback: keep existing function if already present.
-- If your existing save_cart_draft RPC exists, the Customer App will continue using it.

-- Sample product generator: 20 products per category, only inserts names that are absent.
do $$
declare cats text[] := array['Fish','Seafood','Meat','Eggs','Milk','Bakery'];
declare c text; i integer;
begin
 foreach c in array cats loop
  for i in 1..20 loop
   insert into public.fish(name,category,price,unit,available,description)
   select c||' Sample Product '||i,c,case c when 'Fish' then 180+i*5 when 'Seafood' then 220+i*7 when 'Meat' then 260+i*8 when 'Eggs' then 8+i when 'Milk' then 55+i when 'Bakery' then 40+i*3 else 100 end,'KG',true,'Sample product — Admin থেকে price, image, stock ও description customize করুন।'
   where not exists(select 1 from public.fish f where lower(f.name)=lower(c||' Sample Product '||i));
  end loop;
 end loop;
end $$;

-- Realtime for customer tracking (safe if already enabled)
alter table public.delivery_locations replica identity full;

