-- TARAKESWAR FRESH FISH - AUTOMATION V2
-- Run this whole file once in Supabase SQL Editor.
-- Existing public.fish table is preserved.

create extension if not exists pgcrypto;

create table if not exists public.customers (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  mobile text not null unique,
  area text,
  referral_code text unique,
  referred_by uuid references public.customers(id),
  referral_rewarded boolean not null default false,
  fresh_points integer not null default 0,
  wallet_credit numeric(10,2) not null default 0,
  referral_credit_total numeric(10,2) not null default 0,
  total_orders integer not null default 0,
  lifetime_spend numeric(12,2) not null default 0,
  vip_member boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_no text not null unique default ('TFF-' || to_char(now(),'YYMMDD') || '-' || upper(substr(gen_random_uuid()::text,1,6))),
  customer_id uuid not null references public.customers(id) on delete restrict,
  total numeric(12,2) not null default 0,
  status text not null default 'New' check (status in ('New','Confirmed','Delivered','Cancelled')),
  created_at timestamptz not null default now(),
  delivered_at timestamptz,
  points_awarded integer not null default 0,
  feedback_sent_at timestamptz,
  feedback_status text,
  feedback_error text
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id text,
  product_name text not null,
  qty numeric(10,2) not null default 1,
  unit text,
  unit_price numeric(12,2) not null default 0,
  line_total numeric(12,2) not null default 0
);

create table if not exists public.reward_ledger (
  id bigint generated by default as identity primary key,
  customer_id uuid not null references public.customers(id) on delete cascade,
  order_id uuid references public.orders(id) on delete set null,
  kind text not null,
  points integer not null default 0,
  credit numeric(10,2) not null default 0,
  note text,
  created_at timestamptz not null default now()
);

create table if not exists public.offers (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text,
  badge text default '🔥',
  price numeric(12,2),
  start_at timestamptz not null,
  end_at timestamptz not null,
  priority integer not null default 10,
  enabled boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.public_settings (
  id integer primary key default 1 check (id=1),
  feedback_form_url text,
  whatsapp_number text default '918100227692',
  updated_at timestamptz not null default now()
);
insert into public.public_settings(id,whatsapp_number) values(1,'918100227692') on conflict(id) do nothing;

-- If your fish table does not yet have these generic product columns, keep/extend it safely.
alter table public.fish add column if not exists available boolean default true;
alter table public.fish add column if not exists image_url text;
alter table public.fish add column if not exists description text;
alter table public.fish add column if not exists category text default 'Fish';
alter table public.fish add column if not exists unit text default 'KG';

-- Create/update customer + order atomically from the public customer app.
create or replace function public.create_order_with_customer(
 p_name text, p_mobile text, p_area text, p_referral_code text, p_total numeric, p_items jsonb
) returns table(order_id uuid, order_no text, customer_referral_code text)
language plpgsql security definer set search_path=public as $$
declare
 v_mobile text := regexp_replace(coalesce(p_mobile,''),'[^0-9]','','g');
 v_customer public.customers%rowtype;
 v_referrer uuid;
 v_order public.orders%rowtype;
 v_item jsonb;
 v_ref text;
begin
 if length(v_mobile)=12 and left(v_mobile,2)='91' then v_mobile:=right(v_mobile,10); end if;
 if length(v_mobile) <> 10 then raise exception 'Invalid mobile number'; end if;
 if trim(coalesce(p_name,''))='' or trim(coalesce(p_area,''))='' then raise exception 'Name and area required'; end if;

 select * into v_customer from public.customers where mobile=v_mobile;
 if not found then
   v_ref := 'TFF' || upper(substr(md5(v_mobile || clock_timestamp()::text),1,6));
   if p_referral_code is not null and trim(p_referral_code)<>'' then
      select id into v_referrer from public.customers where upper(referral_code)=upper(trim(p_referral_code)) limit 1;
   end if;
   insert into public.customers(name,mobile,area,referral_code,referred_by)
   values(trim(p_name),v_mobile,trim(p_area),v_ref,v_referrer) returning * into v_customer;
 else
   update public.customers set name=trim(p_name),area=trim(p_area),updated_at=now() where id=v_customer.id returning * into v_customer;
 end if;

 insert into public.orders(customer_id,total) values(v_customer.id,greatest(coalesce(p_total,0),0)) returning * into v_order;
 for v_item in select * from jsonb_array_elements(coalesce(p_items,'[]'::jsonb)) loop
   insert into public.order_items(order_id,product_id,product_name,qty,unit,unit_price,line_total)
   values(v_order.id,v_item->>'product_id',coalesce(v_item->>'name','Product'),coalesce((v_item->>'qty')::numeric,1),v_item->>'unit',coalesce((v_item->>'unit_price')::numeric,0),coalesce((v_item->>'line_total')::numeric,0));
 end loop;
 return query select v_order.id,v_order.order_no,v_customer.referral_code;
end $$;

grant execute on function public.create_order_with_customer(text,text,text,text,numeric,jsonb) to anon, authenticated;

-- Automatic Fresh Points + referral milestone + monthly VIP when an order becomes Delivered.
create or replace function public.apply_delivered_rewards() returns trigger
language plpgsql security definer set search_path=public as $$
declare
 v_points int;
 v_month_orders int;
 v_cust public.customers%rowtype;
 v_success_refs int;
 v_target numeric(10,2):=0;
 v_delta numeric(10,2):=0;
begin
 if new.status='Delivered' and old.status is distinct from 'Delivered' then
   v_points := floor(greatest(new.total,0)/500)::int;
   update public.orders set points_awarded=v_points, delivered_at=coalesce(new.delivered_at,now()) where id=new.id;
   update public.customers set fresh_points=fresh_points+v_points,total_orders=total_orders+1,lifetime_spend=lifetime_spend+new.total,updated_at=now() where id=new.customer_id returning * into v_cust;
   if v_points>0 then insert into public.reward_ledger(customer_id,order_id,kind,points,note) values(new.customer_id,new.id,'fresh_points',v_points,'₹500 per Fresh Point'); end if;

   select count(*) into v_month_orders from public.orders where customer_id=new.customer_id and status='Delivered' and coalesce(delivered_at,created_at)>=date_trunc('month',now());
   if v_month_orders>=4 then update public.customers set vip_member=true where id=new.customer_id; end if;

   if v_cust.referred_by is not null and v_cust.referral_rewarded=false then
     update public.customers set referral_rewarded=true where id=new.customer_id;
     select count(*) into v_success_refs from public.customers where referred_by=v_cust.referred_by and referral_rewarded=true;
     v_target := case when v_success_refs>=10 then 400 when v_success_refs>=5 then 200 when v_success_refs>=3 then 100 when v_success_refs>=1 then 30 else 0 end;
     select greatest(v_target-referral_credit_total,0) into v_delta from public.customers where id=v_cust.referred_by;
     if v_delta>0 then
       update public.customers set wallet_credit=wallet_credit+v_delta,referral_credit_total=v_target,vip_member=(vip_member or v_success_refs>=10),updated_at=now() where id=v_cust.referred_by;
       insert into public.reward_ledger(customer_id,order_id,kind,credit,note) values(v_cust.referred_by,new.id,'referral',v_delta,'Successful referral milestone: '||v_success_refs);
     end if;
   end if;
 end if;
 return new;
end $$;

drop trigger if exists trg_apply_delivered_rewards on public.orders;
create trigger trg_apply_delivered_rewards after update of status on public.orders for each row execute function public.apply_delivered_rewards();

-- RLS
alter table public.customers enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.reward_ledger enable row level security;
alter table public.offers enable row level security;
alter table public.public_settings enable row level security;

-- Public customer app can only read current offers/settings. Order writes happen through RPC.
drop policy if exists "public read offers" on public.offers;
create policy "public read offers" on public.offers for select to anon,authenticated using (true);
drop policy if exists "public read settings" on public.public_settings;
create policy "public read settings" on public.public_settings for select to anon,authenticated using (true);

-- Authenticated admin can manage automation tables. Keep Supabase Auth sign-up disabled / only create trusted admin users.
drop policy if exists "admin customers" on public.customers; create policy "admin customers" on public.customers for all to authenticated using (true) with check (true);
drop policy if exists "admin orders" on public.orders; create policy "admin orders" on public.orders for all to authenticated using (true) with check (true);
drop policy if exists "admin items" on public.order_items; create policy "admin items" on public.order_items for all to authenticated using (true) with check (true);
drop policy if exists "admin rewards" on public.reward_ledger; create policy "admin rewards" on public.reward_ledger for all to authenticated using (true) with check (true);
drop policy if exists "admin offers" on public.offers; create policy "admin offers" on public.offers for all to authenticated using (true) with check (true);
drop policy if exists "admin settings" on public.public_settings; create policy "admin settings" on public.public_settings for all to authenticated using (true) with check (true);

-- Optional: put your Google Feedback Form URL here after setup.
-- update public.public_settings set feedback_form_url='https://docs.google.com/forms/d/e/YOUR_FORM/viewform' where id=1;
