-- TARAKESWAR FRESH FISH — V2.3 NEXT-DAY COMMERCE UPGRADE

create extension if not exists pgcrypto;

alter table public.orders add column if not exists delivery_date date;
alter table public.orders add column if not exists delivery_slot text;
alter table public.orders add column if not exists payment_method text default 'COD_ADVANCE';
alter table public.orders add column if not exists advance_percent numeric(5,2) default 20;
alter table public.orders add column if not exists advance_amount numeric(12,2) default 0;
alter table public.orders add column if not exists discount_amount numeric(12,2) default 0;
alter table public.orders add column if not exists payable_total numeric(12,2);
alter table public.orders add column if not exists payment_status text default 'Pending';
alter table public.orders add column if not exists delivery_lat numeric(10,7);
alter table public.orders add column if not exists delivery_lng numeric(10,7);
alter table public.orders add column if not exists location_updated_at timestamptz;
alter table public.orders add column if not exists customer_note text;

alter table public.orders drop constraint if exists orders_status_check;
alter table public.orders add constraint orders_status_check check (
  status in ('New','Confirmed','Preparing','Packed','Out for Delivery','Delivered','Cancelled')
);

alter table public.public_settings add column if not exists cod_advance_percent numeric(5,2) default 20;
alter table public.public_settings add column if not exists online_discount_percent numeric(5,2) default 2;
alter table public.public_settings add column if not exists upi_id text;
alter table public.public_settings add column if not exists delivery_note text default 'আজ রাত ১১:৫৯-এর মধ্যে অর্ডার করলে আগামীকাল ডেলিভারি';
alter table public.public_settings add column if not exists morning_slot text default 'Morning • 7 AM–11 AM';
alter table public.public_settings add column if not exists evening_slot text default 'Evening • 4 PM–8 PM';

create table if not exists public.cart_drafts (
  id uuid primary key default gen_random_uuid(),
  guest_id text not null unique,
  customer_name text,
  mobile text,
  area text,
  items jsonb not null default '[]'::jsonb,
  total numeric(12,2) not null default 0,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.order_status_history (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  status text not null,
  note text,
  created_at timestamptz not null default now()
);

alter table public.cart_drafts enable row level security;
alter table public.order_status_history enable row level security;

drop policy if exists "admin cart drafts" on public.cart_drafts;
create policy "admin cart drafts" on public.cart_drafts for all to authenticated using (true) with check (true);

drop policy if exists "admin status history" on public.order_status_history;
create policy "admin status history" on public.order_status_history for all to authenticated using (true) with check (true);

grant select,insert,update,delete on public.cart_drafts to authenticated;
grant select,insert,update,delete on public.order_status_history to authenticated;
grant usage,select on all sequences in schema public to authenticated;

create or replace function public.save_cart_draft(
  p_guest_id text,
  p_customer_name text,
  p_mobile text,
  p_area text,
  p_items jsonb,
  p_total numeric
) returns void
language plpgsql
security definer
set search_path=public
as $$
begin
  insert into public.cart_drafts(guest_id,customer_name,mobile,area,items,total,updated_at)
  values(trim(p_guest_id),nullif(trim(coalesce(p_customer_name,'')),''),nullif(regexp_replace(coalesce(p_mobile,''),'[^0-9]','','g'),''),nullif(trim(coalesce(p_area,'')),''),coalesce(p_items,'[]'::jsonb),greatest(coalesce(p_total,0),0),now())
  on conflict(guest_id) do update set
    customer_name=excluded.customer_name,
    mobile=excluded.mobile,
    area=excluded.area,
    items=excluded.items,
    total=excluded.total,
    updated_at=now();
end $$;

grant execute on function public.save_cart_draft(text,text,text,text,jsonb,numeric) to anon,authenticated;

create or replace function public.create_order_v3(
 p_name text,
 p_mobile text,
 p_area text,
 p_referral_code text,
 p_total numeric,
 p_items jsonb,
 p_delivery_date date,
 p_delivery_slot text,
 p_payment_method text,
 p_advance_percent numeric,
 p_advance_amount numeric,
 p_discount_amount numeric,
 p_payable_total numeric,
 p_customer_note text,
 p_guest_id text
)
returns table(order_id uuid, order_no text, customer_referral_code text)
language plpgsql
security definer
set search_path=public
as $$
declare
 v_mobile text:=regexp_replace(coalesce(p_mobile,''),'[^0-9]','','g');
 v_customer public.customers%rowtype;
 v_referrer uuid;
 v_order public.orders%rowtype;
 v_item jsonb;
 v_ref text;
begin
 if length(v_mobile)=12 and left(v_mobile,2)='91' then v_mobile:=right(v_mobile,10); end if;
 if length(v_mobile)<>10 then raise exception 'Invalid mobile number'; end if;
 if trim(coalesce(p_name,''))='' or trim(coalesce(p_area,''))='' then raise exception 'Name and area required'; end if;

 select * into v_customer from public.customers where mobile=v_mobile;
 if not found then
   v_ref:='TFF'||upper(substr(md5(v_mobile||clock_timestamp()::text),1,6));
   if nullif(trim(coalesce(p_referral_code,'')),'') is not null then
     select id into v_referrer from public.customers where upper(referral_code)=upper(trim(p_referral_code)) limit 1;
   end if;
   insert into public.customers(name,mobile,area,referral_code,referred_by)
   values(trim(p_name),v_mobile,trim(p_area),v_ref,v_referrer)
   returning * into v_customer;
 else
   update public.customers set name=trim(p_name),area=trim(p_area),updated_at=now() where id=v_customer.id returning * into v_customer;
 end if;

 insert into public.orders(customer_id,total,status,delivery_date,delivery_slot,payment_method,advance_percent,advance_amount,discount_amount,payable_total,payment_status,customer_note)
 values(v_customer.id,greatest(coalesce(p_total,0),0),'New',p_delivery_date,p_delivery_slot,coalesce(p_payment_method,'COD_ADVANCE'),greatest(coalesce(p_advance_percent,0),0),greatest(coalesce(p_advance_amount,0),0),greatest(coalesce(p_discount_amount,0),0),greatest(coalesce(p_payable_total,p_total),0),'Pending',nullif(trim(coalesce(p_customer_note,'')),''))
 returning * into v_order;

 for v_item in select * from jsonb_array_elements(coalesce(p_items,'[]'::jsonb)) loop
   insert into public.order_items(order_id,product_id,product_name,qty,unit,unit_price,line_total)
   values(v_order.id,v_item->>'product_id',coalesce(v_item->>'name','Product'),coalesce((v_item->>'qty')::numeric,1),v_item->>'unit',coalesce((v_item->>'unit_price')::numeric,0),coalesce((v_item->>'line_total')::numeric,0));
 end loop;

 insert into public.order_status_history(order_id,status,note) values(v_order.id,'New','Order placed by customer');
 if nullif(trim(coalesce(p_guest_id,'')),'') is not null then delete from public.cart_drafts where guest_id=trim(p_guest_id); end if;

 return query select v_order.id,v_order.order_no,v_customer.referral_code;
end $$;

grant execute on function public.create_order_v3(text,text,text,text,numeric,jsonb,date,text,text,numeric,numeric,numeric,numeric,text,text) to anon,authenticated;

create or replace function public.track_order(p_order_no text,p_mobile text)
returns table(
 order_no text,status text,delivery_date date,delivery_slot text,payment_method text,
 advance_amount numeric,discount_amount numeric,payable_total numeric,payment_status text,
 delivery_lat numeric,delivery_lng numeric,location_updated_at timestamptz,created_at timestamptz
)
language sql
security definer
set search_path=public
as $$
 select o.order_no,o.status,o.delivery_date,o.delivery_slot,o.payment_method,o.advance_amount,o.discount_amount,
        coalesce(o.payable_total,o.total),o.payment_status,o.delivery_lat,o.delivery_lng,o.location_updated_at,o.created_at
 from public.orders o join public.customers c on c.id=o.customer_id
 where upper(o.order_no)=upper(trim(p_order_no))
   and right(regexp_replace(c.mobile,'[^0-9]','','g'),10)=right(regexp_replace(coalesce(p_mobile,''),'[^0-9]','','g'),10)
 limit 1;
$$;

grant execute on function public.track_order(text,text) to anon,authenticated;

create or replace function public.log_order_status_change()
returns trigger language plpgsql security definer set search_path=public as $$
begin
 if old.status is distinct from new.status then
   insert into public.order_status_history(order_id,status,note) values(new.id,new.status,'Status updated');
 end if;
 return new;
end $$;

drop trigger if exists trg_order_status_history on public.orders;
create trigger trg_order_status_history after update of status on public.orders for each row execute function public.log_order_status_change();
