-- Tarakeswar Fresh Fish V6 master migration
-- Run this AFTER the existing V5/V5.3 migrations in the same Supabase project.

alter table if exists public.fish add column if not exists stock_qty numeric not null default 0;
alter table if exists public.fish add column if not exists low_stock_threshold numeric not null default 5;
alter table if exists public.fish add column if not exists tags text[] not null default '{}';
alter table if exists public.fish add column if not exists preparation text;

create table if not exists public.ai_product_jobs(
 id bigint generated by default as identity primary key,
 created_at timestamptz not null default now(),
 created_by uuid null,
 image_url text,
 input_hint text,
 draft jsonb not null default '{}',
 status text not null default 'draft'
);
create table if not exists public.automation_events(
 id bigint generated by default as identity primary key,
 created_at timestamptz not null default now(),
 event_type text not null,
 entity_type text,
 entity_id text,
 payload jsonb not null default '{}',
 status text not null default 'queued',
 attempts int not null default 0,
 last_error text
);
create table if not exists public.ai_action_log(
 id bigint generated by default as identity primary key,
 created_at timestamptz not null default now(),
 actor_type text not null,
 actor_id uuid null,
 action_type text not null,
 payload jsonb not null default '{}',
 status text not null default 'approved'
);

insert into storage.buckets(id,name,public) values('product-images','product-images',true) on conflict(id) do update set public=true;

drop policy if exists "public read product images" on storage.objects;
create policy "public read product images" on storage.objects for select to anon,authenticated using(bucket_id='product-images');

-- Basic RLS for V6 logs: admins can access through service role; customer clients do not need direct access.
alter table public.ai_product_jobs enable row level security;
alter table public.automation_events enable row level security;
alter table public.ai_action_log enable row level security;
